###

GET http://{{host}} HTTP/1.1
Content-Type: text/plain

###

GET http://{{host}}/books HTTP/1.1
Content-Type: application/json

###

GET http://{{host}}/books/5d204b3faade0d7b820a2eed HTTP/1.1
Content-Type: application/json

###

POST http://{{host}}/books HTTP/1.1
content-type: application/json

{
    "title": "Game of Throne",
    "author": "RR",
    "category": "Fantasy"
}

###

POST http://{{host}}/books2 HTTP/1.1
content-type: application/json

{
    "title": "Return of the King",
    "author": "RR",
    "category": "Fantasy"
}

###

PUT http://{{host}}/books/5d2057e19fad360ca44a0a79 HTTP/1.1
content-type: application/json

{
    "title": "Return of the Jack"
}

###

DELETE http://{{host}}/books/5d205bbe0579590fedf89771 HTTP/1.1
content-type: application/json



